"""empty message

Revision ID: 401af571658c
Revises: 7938dbce1a32
Create Date: 2023-12-17 13:22:12.082072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401af571658c'
down_revision = '7938dbce1a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
